#! /bin/bash

time \
./find_dead_pixels /home/annex/astronomy/great_bear_dark_sky/images/2019/11/01/tif/0001.tif \
                   /home/annex/astronomy/great_bear_dark_sky/images/2019/11/01/tif/0002.tif





