#! /bin/bash

list_pixels_2 \
  /home/annex/astronomy/great_bear_dark_sky/images/2019/11/01/tif/0001.tif \
  /home/annex/astronomy/great_bear_dark_sky/images/2019/11/01/tif/0002.tif \
  0 15 > ./result


